#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=104
#SBATCH --mem-per-cpu=2000
#SBATCH --time=08:00:00
#SBATCH --job-name=s_cube

# load python
module load release/24.04  GCCcore/13.3.0
module load Python/3.12.3

# activate venv
source s_cube_venv/bin/activate

# add the path to s_cube
. source_path

# path to the python script
cd examples/ || exit

python3 s3_for_cylinder3D_Re3900.py &> "log.main"
