#!/bin/bash

# Get the absolute path to the project root
S_CUBE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Set the PYTHONPATH to include the project root
export PYTHONPATH="${S_CUBE}:${PYTHONPATH}"

